// src/config/columnMetadata.js

const columnMetadata = {
  Banco: {
    id: "ID_BANCO",
    columns: [
      {
        nombre: "ID_BANCO",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NOMBRE_BANCO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS",
        tipo: "int",
        visible: true,
        editable: false,
        inputType: "number",
      },
      {
        nombre: "CREATED_AT",
        tipo: "datetime2",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "UPDATED_AT",
        tipo: "datetime2",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
    ],
  },
  CentroCosto: {
    id: "ID_CENTRO_COSTO",
    columns: [
      {
        nombre: "ID_CENTRO_COSTO",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CODIGO_CENTRO_COSTO",
        tipo: "nvarchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "NOMBRE",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS",
        tipo: "varchar",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "ID_GERENTE",
        tipo: "int",
        visible: true,
        editable: true,
        inputType: "select",
      },
      {
        nombre: "CREATE_AT",
        tipo: "timestamp",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CREATE_UPDATE",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NIVEL",
        tipo: "int",
        visible: true,
        editable: true,
        inputType: "number",
      },
      {
        nombre: "MONTO",
        tipo: "decimal",
        visible: true,
        editable: true,
        inputType: "number",
      },
      {
        nombre: "Gerente_Detalle",
        tipo: "varchar",
        visible: true,
        editable: false,
        inputType: "text",
      },
    ],
  },
  Cuentas: {
    id: "ID_CUENTA",
    columns: [
      {
        nombre: "ID_CUENTA",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CODIGO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "NOMBRE_CUENTA",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
    ],
  },
  Empresa: {
    id: "ID_EMPRESA",
    columns: [
      {
        nombre: "ID_EMPRESA",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NOMBRE",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "DOCUMENTO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "GIRO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "DIRECCION",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "TELEFONO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "CORREO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "email",
      },
      {
        nombre: "ENCARGADO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS_CENTRO_COSTO",
        tipo: "varchar",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "ELIMINADO",
        tipo: "int",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_CREACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "date",
      },
      {
        nombre: "FECHA_ACTUALIZACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
    ],
  },
  Monedas: {
    id: "ID_MONEDA",
    columns: [
      {
        nombre: "ID_MONEDA",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "ABREV",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "NOMBRE",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "FECHA_CREACION",
        tipo: "datetime",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_SISTEMA",
        tipo: "timestamp",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CAMBIO",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
    ],
  },
  PlazoPago: {
    id: "ID_FORMA_PAGO",
    columns: [
      {
        nombre: "ID_FORMA_PAGO",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NOMBRE",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS_FORMA_PAGO",
        tipo: "bit",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_CREACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_ACTUALIZACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
    ],
  },
  Producto: {
    id: "ID_PRODUCTO",
    columns: [
      {
        nombre: "ID_PRODUCTO",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "DESCRIPCION",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "UNIDAD",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "PRESENTACION",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS_PRODUCTO",
        tipo: "bit",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_CREACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_ACTUALIZACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
    ],
  },
  Proveedor: {
    id: "ID_PROVEEDOR",
    columns: [
      {
        nombre: "ID_PROVEEDOR",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NOMBRE_PROVEEDOR",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "DOCUMENTO_PROVEEDOR",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "TELEFONO_PRINCIPAL",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "CORREO_PRINCIPAL",
        tipo: "varchar",
        visible: true,
        editable: true,
        inputType: "email",
      },
      {
        nombre: "ESTATUS_PROVEEDOR",
        tipo: "varchar",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_CREACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "FECHA_ACTUALIZACION",
        tipo: "date",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "ELIMINADO",
        tipo: "int",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "Bancos_Asociados",
        tipo: "varchar",
        visible: true,
        editable: false,
        inputType: "text",
      },
    ],
  },
  TipoOrden: {
    id: "ID_TIPO",
    columns: [
      {
        nombre: "ID_TIPO",
        tipo: "int",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CREATED_AT",
        tipo: "datetime",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "CREADO_POR",
        tipo: "nvarchar",
        visible: true,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "UPDATED_AT",
        tipo: "datetime",
        visible: false,
        editable: false,
        inputType: "hidden",
      },
      {
        nombre: "NOMBRE",
        tipo: "nvarchar",
        visible: true,
        editable: true,
        inputType: "text",
      },
      {
        nombre: "ESTATUS_TIPO_ORDEN",
        tipo: "bit",
        visible: true,
        editable: false,
        inputType: "number",
      },
      {
        nombre: "Detalles_Asociados",
        tipo: "nvarchar",
        visible: true,
        editable: false,
        inputType: "text",
      },
    ],
  },
};

export default columnMetadata;
